[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_backend"

[project]
name = "llm-decision-robustness"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]